version: "3.3"

services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - config-server-network

networks:
  config-server-network:
    driver: bridge