server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/lucaswerner/my-card-apps-config
          search-paths: my-card-cards, my-card-transactions, my-card-users